server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: inventory
          uri: http://localhost:8082
          predicates:
            - Path=/inventories/**, 
        - id: basic
          uri: http://localhost:8083
          predicates:
            - Path=/companies/**, 
        - id: bound
          uri: http://localhost:8084
          predicates:
            - Path=/dispas/**, 
        - id: Project A
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, 
        - id: basic
          uri: http://basic:8080
          predicates:
            - Path=/companies/**, 
        - id: bound
          uri: http://bound:8080
          predicates:
            - Path=/dispas/**, 
        - id: Project A
          uri: http://projectA:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
